export interface Country {
  code: string;
  name: string;
  dialCode: string;
  flag: string;
}

export const countries: Country[] = [
  { code: "AF", name: "Afghanistan", dialCode: "+93", flag: "\u{1F1E6}\u{1F1EB}" },
  { code: "AL", name: "Albania", dialCode: "+355", flag: "\u{1F1E6}\u{1F1F1}" },
  { code: "DZ", name: "Algeria", dialCode: "+213", flag: "\u{1F1E9}\u{1F1FF}" },
  { code: "AS", name: "American Samoa", dialCode: "+1684", flag: "\u{1F1E6}\u{1F1F8}" },
  { code: "AD", name: "Andorra", dialCode: "+376", flag: "\u{1F1E6}\u{1F1E9}" },
  { code: "AO", name: "Angola", dialCode: "+244", flag: "\u{1F1E6}\u{1F1F4}" },
  { code: "AI", name: "Anguilla", dialCode: "+1264", flag: "\u{1F1E6}\u{1F1EE}" },
  { code: "AQ", name: "Antarctica", dialCode: "+672", flag: "\u{1F1E6}\u{1F1F6}" },
  { code: "AG", name: "Antigua and Barbuda", dialCode: "+1268", flag: "\u{1F1E6}\u{1F1EC}" },
  { code: "AR", name: "Argentina", dialCode: "+54", flag: "\u{1F1E6}\u{1F1F7}" },
  { code: "AM", name: "Armenia", dialCode: "+374", flag: "\u{1F1E6}\u{1F1F2}" },
  { code: "AW", name: "Aruba", dialCode: "+297", flag: "\u{1F1E6}\u{1F1FC}" },
  { code: "AU", name: "Australia", dialCode: "+61", flag: "\u{1F1E6}\u{1F1FA}" },
  { code: "AT", name: "Austria", dialCode: "+43", flag: "\u{1F1E6}\u{1F1F9}" },
  { code: "AZ", name: "Azerbaijan", dialCode: "+994", flag: "\u{1F1E6}\u{1F1FF}" },
  { code: "BS", name: "Bahamas", dialCode: "+1242", flag: "\u{1F1E7}\u{1F1F8}" },
  { code: "BH", name: "Bahrain", dialCode: "+973", flag: "\u{1F1E7}\u{1F1ED}" },
  { code: "BD", name: "Bangladesh", dialCode: "+880", flag: "\u{1F1E7}\u{1F1E9}" },
  { code: "BB", name: "Barbados", dialCode: "+1246", flag: "\u{1F1E7}\u{1F1E7}" },
  { code: "BY", name: "Belarus", dialCode: "+375", flag: "\u{1F1E7}\u{1F1FE}" },
  { code: "BE", name: "Belgium", dialCode: "+32", flag: "\u{1F1E7}\u{1F1EA}" },
  { code: "BZ", name: "Belize", dialCode: "+501", flag: "\u{1F1E7}\u{1F1FF}" },
  { code: "BJ", name: "Benin", dialCode: "+229", flag: "\u{1F1E7}\u{1F1EF}" },
  { code: "BM", name: "Bermuda", dialCode: "+1441", flag: "\u{1F1E7}\u{1F1F2}" },
  { code: "BT", name: "Bhutan", dialCode: "+975", flag: "\u{1F1E7}\u{1F1F9}" },
  { code: "BO", name: "Bolivia", dialCode: "+591", flag: "\u{1F1E7}\u{1F1F4}" },
  { code: "BA", name: "Bosnia and Herzegovina", dialCode: "+387", flag: "\u{1F1E7}\u{1F1E6}" },
  { code: "BW", name: "Botswana", dialCode: "+267", flag: "\u{1F1E7}\u{1F1FC}" },
  { code: "BR", name: "Brazil", dialCode: "+55", flag: "\u{1F1E7}\u{1F1F7}" },
  { code: "IO", name: "British Indian Ocean Territory", dialCode: "+246", flag: "\u{1F1EE}\u{1F1F4}" },
  { code: "VG", name: "British Virgin Islands", dialCode: "+1284", flag: "\u{1F1FB}\u{1F1EC}" },
  { code: "BN", name: "Brunei", dialCode: "+673", flag: "\u{1F1E7}\u{1F1F3}" },
  { code: "BG", name: "Bulgaria", dialCode: "+359", flag: "\u{1F1E7}\u{1F1EC}" },
  { code: "BF", name: "Burkina Faso", dialCode: "+226", flag: "\u{1F1E7}\u{1F1EB}" },
  { code: "BI", name: "Burundi", dialCode: "+257", flag: "\u{1F1E7}\u{1F1EE}" },
  { code: "KH", name: "Cambodia", dialCode: "+855", flag: "\u{1F1F0}\u{1F1ED}" },
  { code: "CM", name: "Cameroon", dialCode: "+237", flag: "\u{1F1E8}\u{1F1F2}" },
  { code: "CA", name: "Canada", dialCode: "+1", flag: "\u{1F1E8}\u{1F1E6}" },
  { code: "CV", name: "Cape Verde", dialCode: "+238", flag: "\u{1F1E8}\u{1F1FB}" },
  { code: "KY", name: "Cayman Islands", dialCode: "+1345", flag: "\u{1F1F0}\u{1F1FE}" },
  { code: "CF", name: "Central African Republic", dialCode: "+236", flag: "\u{1F1E8}\u{1F1EB}" },
  { code: "TD", name: "Chad", dialCode: "+235", flag: "\u{1F1F9}\u{1F1E9}" },
  { code: "CL", name: "Chile", dialCode: "+56", flag: "\u{1F1E8}\u{1F1F1}" },
  { code: "CN", name: "China", dialCode: "+86", flag: "\u{1F1E8}\u{1F1F3}" },
  { code: "CX", name: "Christmas Island", dialCode: "+61", flag: "\u{1F1E8}\u{1F1FD}" },
  { code: "CC", name: "Cocos (Keeling) Islands", dialCode: "+61", flag: "\u{1F1E8}\u{1F1E8}" },
  { code: "CO", name: "Colombia", dialCode: "+57", flag: "\u{1F1E8}\u{1F1F4}" },
  { code: "KM", name: "Comoros", dialCode: "+269", flag: "\u{1F1F0}\u{1F1F2}" },
  { code: "CK", name: "Cook Islands", dialCode: "+682", flag: "\u{1F1E8}\u{1F1F0}" },
  { code: "CR", name: "Costa Rica", dialCode: "+506", flag: "\u{1F1E8}\u{1F1F7}" },
  { code: "HR", name: "Croatia", dialCode: "+385", flag: "\u{1F1ED}\u{1F1F7}" },
  { code: "CU", name: "Cuba", dialCode: "+53", flag: "\u{1F1E8}\u{1F1FA}" },
  { code: "CW", name: "Curacao", dialCode: "+599", flag: "\u{1F1E8}\u{1F1FC}" },
  { code: "CY", name: "Cyprus", dialCode: "+357", flag: "\u{1F1E8}\u{1F1FE}" },
  { code: "CZ", name: "Czech Republic", dialCode: "+420", flag: "\u{1F1E8}\u{1F1FF}" },
  { code: "CD", name: "Democratic Republic of the Congo", dialCode: "+243", flag: "\u{1F1E8}\u{1F1E9}" },
  { code: "DK", name: "Denmark", dialCode: "+45", flag: "\u{1F1E9}\u{1F1F0}" },
  { code: "DJ", name: "Djibouti", dialCode: "+253", flag: "\u{1F1E9}\u{1F1EF}" },
  { code: "DM", name: "Dominica", dialCode: "+1767", flag: "\u{1F1E9}\u{1F1F2}" },
  { code: "DO", name: "Dominican Republic", dialCode: "+1849", flag: "\u{1F1E9}\u{1F1F4}" },
  { code: "TL", name: "East Timor", dialCode: "+670", flag: "\u{1F1F9}\u{1F1F1}" },
  { code: "EC", name: "Ecuador", dialCode: "+593", flag: "\u{1F1EA}\u{1F1E8}" },
  { code: "EG", name: "Egypt", dialCode: "+20", flag: "\u{1F1EA}\u{1F1EC}" },
  { code: "SV", name: "El Salvador", dialCode: "+503", flag: "\u{1F1F8}\u{1F1FB}" },
  { code: "GQ", name: "Equatorial Guinea", dialCode: "+240", flag: "\u{1F1EC}\u{1F1F6}" },
  { code: "ER", name: "Eritrea", dialCode: "+291", flag: "\u{1F1EA}\u{1F1F7}" },
  { code: "EE", name: "Estonia", dialCode: "+372", flag: "\u{1F1EA}\u{1F1EA}" },
  { code: "SZ", name: "Eswatini", dialCode: "+268", flag: "\u{1F1F8}\u{1F1FF}" },
  { code: "ET", name: "Ethiopia", dialCode: "+251", flag: "\u{1F1EA}\u{1F1F9}" },
  { code: "FK", name: "Falkland Islands", dialCode: "+500", flag: "\u{1F1EB}\u{1F1F0}" },
  { code: "FO", name: "Faroe Islands", dialCode: "+298", flag: "\u{1F1EB}\u{1F1F4}" },
  { code: "FJ", name: "Fiji", dialCode: "+679", flag: "\u{1F1EB}\u{1F1EF}" },
  { code: "FI", name: "Finland", dialCode: "+358", flag: "\u{1F1EB}\u{1F1EE}" },
  { code: "FR", name: "France", dialCode: "+33", flag: "\u{1F1EB}\u{1F1F7}" },
  { code: "GF", name: "French Guiana", dialCode: "+594", flag: "\u{1F1EC}\u{1F1EB}" },
  { code: "PF", name: "French Polynesia", dialCode: "+689", flag: "\u{1F1F5}\u{1F1EB}" },
  { code: "GA", name: "Gabon", dialCode: "+241", flag: "\u{1F1EC}\u{1F1E6}" },
  { code: "GM", name: "Gambia", dialCode: "+220", flag: "\u{1F1EC}\u{1F1F2}" },
  { code: "GE", name: "Georgia", dialCode: "+995", flag: "\u{1F1EC}\u{1F1EA}" },
  { code: "DE", name: "Germany", dialCode: "+49", flag: "\u{1F1E9}\u{1F1EA}" },
  { code: "GH", name: "Ghana", dialCode: "+233", flag: "\u{1F1EC}\u{1F1ED}" },
  { code: "GI", name: "Gibraltar", dialCode: "+350", flag: "\u{1F1EC}\u{1F1EE}" },
  { code: "GR", name: "Greece", dialCode: "+30", flag: "\u{1F1EC}\u{1F1F7}" },
  { code: "GL", name: "Greenland", dialCode: "+299", flag: "\u{1F1EC}\u{1F1F1}" },
  { code: "GD", name: "Grenada", dialCode: "+1473", flag: "\u{1F1EC}\u{1F1E9}" },
  { code: "GP", name: "Guadeloupe", dialCode: "+590", flag: "\u{1F1EC}\u{1F1F5}" },
  { code: "GU", name: "Guam", dialCode: "+1671", flag: "\u{1F1EC}\u{1F1FA}" },
  { code: "GT", name: "Guatemala", dialCode: "+502", flag: "\u{1F1EC}\u{1F1F9}" },
  { code: "GG", name: "Guernsey", dialCode: "+44", flag: "\u{1F1EC}\u{1F1EC}" },
  { code: "GN", name: "Guinea", dialCode: "+224", flag: "\u{1F1EC}\u{1F1F3}" },
  { code: "GW", name: "Guinea-Bissau", dialCode: "+245", flag: "\u{1F1EC}\u{1F1FC}" },
  { code: "GY", name: "Guyana", dialCode: "+592", flag: "\u{1F1EC}\u{1F1FE}" },
  { code: "HT", name: "Haiti", dialCode: "+509", flag: "\u{1F1ED}\u{1F1F9}" },
  { code: "HN", name: "Honduras", dialCode: "+504", flag: "\u{1F1ED}\u{1F1F3}" },
  { code: "HK", name: "Hong Kong", dialCode: "+852", flag: "\u{1F1ED}\u{1F1F0}" },
  { code: "HU", name: "Hungary", dialCode: "+36", flag: "\u{1F1ED}\u{1F1FA}" },
  { code: "IS", name: "Iceland", dialCode: "+354", flag: "\u{1F1EE}\u{1F1F8}" },
  { code: "IN", name: "India", dialCode: "+91", flag: "\u{1F1EE}\u{1F1F3}" },
  { code: "ID", name: "Indonesia", dialCode: "+62", flag: "\u{1F1EE}\u{1F1E9}" },
  { code: "IR", name: "Iran", dialCode: "+98", flag: "\u{1F1EE}\u{1F1F7}" },
  { code: "IQ", name: "Iraq", dialCode: "+964", flag: "\u{1F1EE}\u{1F1F6}" },
  { code: "IE", name: "Ireland", dialCode: "+353", flag: "\u{1F1EE}\u{1F1EA}" },
  { code: "IM", name: "Isle of Man", dialCode: "+44", flag: "\u{1F1EE}\u{1F1F2}" },
  { code: "IL", name: "Israel", dialCode: "+972", flag: "\u{1F1EE}\u{1F1F1}" },
  { code: "IT", name: "Italy", dialCode: "+39", flag: "\u{1F1EE}\u{1F1F9}" },
  { code: "CI", name: "Ivory Coast", dialCode: "+225", flag: "\u{1F1E8}\u{1F1EE}" },
  { code: "JM", name: "Jamaica", dialCode: "+1876", flag: "\u{1F1EF}\u{1F1F2}" },
  { code: "JP", name: "Japan", dialCode: "+81", flag: "\u{1F1EF}\u{1F1F5}" },
  { code: "JE", name: "Jersey", dialCode: "+44", flag: "\u{1F1EF}\u{1F1EA}" },
  { code: "JO", name: "Jordan", dialCode: "+962", flag: "\u{1F1EF}\u{1F1F4}" },
  { code: "KZ", name: "Kazakhstan", dialCode: "+7", flag: "\u{1F1F0}\u{1F1FF}" },
  { code: "KE", name: "Kenya", dialCode: "+254", flag: "\u{1F1F0}\u{1F1EA}" },
  { code: "KI", name: "Kiribati", dialCode: "+686", flag: "\u{1F1F0}\u{1F1EE}" },
  { code: "XK", name: "Kosovo", dialCode: "+383", flag: "\u{1F1FD}\u{1F1F0}" },
  { code: "KW", name: "Kuwait", dialCode: "+965", flag: "\u{1F1F0}\u{1F1FC}" },
  { code: "KG", name: "Kyrgyzstan", dialCode: "+996", flag: "\u{1F1F0}\u{1F1EC}" },
  { code: "LA", name: "Laos", dialCode: "+856", flag: "\u{1F1F1}\u{1F1E6}" },
  { code: "LV", name: "Latvia", dialCode: "+371", flag: "\u{1F1F1}\u{1F1FB}" },
  { code: "LB", name: "Lebanon", dialCode: "+961", flag: "\u{1F1F1}\u{1F1E7}" },
  { code: "LS", name: "Lesotho", dialCode: "+266", flag: "\u{1F1F1}\u{1F1F8}" },
  { code: "LR", name: "Liberia", dialCode: "+231", flag: "\u{1F1F1}\u{1F1F7}" },
  { code: "LY", name: "Libya", dialCode: "+218", flag: "\u{1F1F1}\u{1F1FE}" },
  { code: "LI", name: "Liechtenstein", dialCode: "+423", flag: "\u{1F1F1}\u{1F1EE}" },
  { code: "LT", name: "Lithuania", dialCode: "+370", flag: "\u{1F1F1}\u{1F1F9}" },
  { code: "LU", name: "Luxembourg", dialCode: "+352", flag: "\u{1F1F1}\u{1F1FA}" },
  { code: "MO", name: "Macau", dialCode: "+853", flag: "\u{1F1F2}\u{1F1F4}" },
  { code: "MG", name: "Madagascar", dialCode: "+261", flag: "\u{1F1F2}\u{1F1EC}" },
  { code: "MW", name: "Malawi", dialCode: "+265", flag: "\u{1F1F2}\u{1F1FC}" },
  { code: "MY", name: "Malaysia", dialCode: "+60", flag: "\u{1F1F2}\u{1F1FE}" },
  { code: "MV", name: "Maldives", dialCode: "+960", flag: "\u{1F1F2}\u{1F1FB}" },
  { code: "ML", name: "Mali", dialCode: "+223", flag: "\u{1F1F2}\u{1F1F1}" },
  { code: "MT", name: "Malta", dialCode: "+356", flag: "\u{1F1F2}\u{1F1F9}" },
  { code: "MH", name: "Marshall Islands", dialCode: "+692", flag: "\u{1F1F2}\u{1F1ED}" },
  { code: "MQ", name: "Martinique", dialCode: "+596", flag: "\u{1F1F2}\u{1F1F6}" },
  { code: "MR", name: "Mauritania", dialCode: "+222", flag: "\u{1F1F2}\u{1F1F7}" },
  { code: "MU", name: "Mauritius", dialCode: "+230", flag: "\u{1F1F2}\u{1F1FA}" },
  { code: "YT", name: "Mayotte", dialCode: "+262", flag: "\u{1F1FE}\u{1F1F9}" },
  { code: "MX", name: "Mexico", dialCode: "+52", flag: "\u{1F1F2}\u{1F1FD}" },
  { code: "FM", name: "Micronesia", dialCode: "+691", flag: "\u{1F1EB}\u{1F1F2}" },
  { code: "MD", name: "Moldova", dialCode: "+373", flag: "\u{1F1F2}\u{1F1E9}" },
  { code: "MC", name: "Monaco", dialCode: "+377", flag: "\u{1F1F2}\u{1F1E8}" },
  { code: "MN", name: "Mongolia", dialCode: "+976", flag: "\u{1F1F2}\u{1F1F3}" },
  { code: "ME", name: "Montenegro", dialCode: "+382", flag: "\u{1F1F2}\u{1F1EA}" },
  { code: "MS", name: "Montserrat", dialCode: "+1664", flag: "\u{1F1F2}\u{1F1F8}" },
  { code: "MA", name: "Morocco", dialCode: "+212", flag: "\u{1F1F2}\u{1F1E6}" },
  { code: "MZ", name: "Mozambique", dialCode: "+258", flag: "\u{1F1F2}\u{1F1FF}" },
  { code: "MM", name: "Myanmar", dialCode: "+95", flag: "\u{1F1F2}\u{1F1F2}" },
  { code: "NA", name: "Namibia", dialCode: "+264", flag: "\u{1F1F3}\u{1F1E6}" },
  { code: "NR", name: "Nauru", dialCode: "+674", flag: "\u{1F1F3}\u{1F1F7}" },
  { code: "NP", name: "Nepal", dialCode: "+977", flag: "\u{1F1F3}\u{1F1F5}" },
  { code: "NL", name: "Netherlands", dialCode: "+31", flag: "\u{1F1F3}\u{1F1F1}" },
  { code: "NC", name: "New Caledonia", dialCode: "+687", flag: "\u{1F1F3}\u{1F1E8}" },
  { code: "NZ", name: "New Zealand", dialCode: "+64", flag: "\u{1F1F3}\u{1F1FF}" },
  { code: "NI", name: "Nicaragua", dialCode: "+505", flag: "\u{1F1F3}\u{1F1EE}" },
  { code: "NE", name: "Niger", dialCode: "+227", flag: "\u{1F1F3}\u{1F1EA}" },
  { code: "NG", name: "Nigeria", dialCode: "+234", flag: "\u{1F1F3}\u{1F1EC}" },
  { code: "NU", name: "Niue", dialCode: "+683", flag: "\u{1F1F3}\u{1F1FA}" },
  { code: "NF", name: "Norfolk Island", dialCode: "+672", flag: "\u{1F1F3}\u{1F1EB}" },
  { code: "KP", name: "North Korea", dialCode: "+850", flag: "\u{1F1F0}\u{1F1F5}" },
  { code: "MK", name: "North Macedonia", dialCode: "+389", flag: "\u{1F1F2}\u{1F1F0}" },
  { code: "MP", name: "Northern Mariana Islands", dialCode: "+1670", flag: "\u{1F1F2}\u{1F1F5}" },
  { code: "NO", name: "Norway", dialCode: "+47", flag: "\u{1F1F3}\u{1F1F4}" },
  { code: "OM", name: "Oman", dialCode: "+968", flag: "\u{1F1F4}\u{1F1F2}" },
  { code: "PK", name: "Pakistan", dialCode: "+92", flag: "\u{1F1F5}\u{1F1F0}" },
  { code: "PW", name: "Palau", dialCode: "+680", flag: "\u{1F1F5}\u{1F1FC}" },
  { code: "PS", name: "Palestine", dialCode: "+970", flag: "\u{1F1F5}\u{1F1F8}" },
  { code: "PA", name: "Panama", dialCode: "+507", flag: "\u{1F1F5}\u{1F1E6}" },
  { code: "PG", name: "Papua New Guinea", dialCode: "+675", flag: "\u{1F1F5}\u{1F1EC}" },
  { code: "PY", name: "Paraguay", dialCode: "+595", flag: "\u{1F1F5}\u{1F1FE}" },
  { code: "PE", name: "Peru", dialCode: "+51", flag: "\u{1F1F5}\u{1F1EA}" },
  { code: "PH", name: "Philippines", dialCode: "+63", flag: "\u{1F1F5}\u{1F1ED}" },
  { code: "PN", name: "Pitcairn Islands", dialCode: "+64", flag: "\u{1F1F5}\u{1F1F3}" },
  { code: "PL", name: "Poland", dialCode: "+48", flag: "\u{1F1F5}\u{1F1F1}" },
  { code: "PT", name: "Portugal", dialCode: "+351", flag: "\u{1F1F5}\u{1F1F9}" },
  { code: "PR", name: "Puerto Rico", dialCode: "+1787", flag: "\u{1F1F5}\u{1F1F7}" },
  { code: "QA", name: "Qatar", dialCode: "+974", flag: "\u{1F1F6}\u{1F1E6}" },
  { code: "CG", name: "Republic of the Congo", dialCode: "+242", flag: "\u{1F1E8}\u{1F1EC}" },
  { code: "RE", name: "Reunion", dialCode: "+262", flag: "\u{1F1F7}\u{1F1EA}" },
  { code: "RO", name: "Romania", dialCode: "+40", flag: "\u{1F1F7}\u{1F1F4}" },
  { code: "RU", name: "Russia", dialCode: "+7", flag: "\u{1F1F7}\u{1F1FA}" },
  { code: "RW", name: "Rwanda", dialCode: "+250", flag: "\u{1F1F7}\u{1F1FC}" },
  { code: "BL", name: "Saint Barthelemy", dialCode: "+590", flag: "\u{1F1E7}\u{1F1F1}" },
  { code: "SH", name: "Saint Helena", dialCode: "+290", flag: "\u{1F1F8}\u{1F1ED}" },
  { code: "KN", name: "Saint Kitts and Nevis", dialCode: "+1869", flag: "\u{1F1F0}\u{1F1F3}" },
  { code: "LC", name: "Saint Lucia", dialCode: "+1758", flag: "\u{1F1F1}\u{1F1E8}" },
  { code: "MF", name: "Saint Martin", dialCode: "+590", flag: "\u{1F1F2}\u{1F1EB}" },
  { code: "PM", name: "Saint Pierre and Miquelon", dialCode: "+508", flag: "\u{1F1F5}\u{1F1F2}" },
  { code: "VC", name: "Saint Vincent and the Grenadines", dialCode: "+1784", flag: "\u{1F1FB}\u{1F1E8}" },
  { code: "WS", name: "Samoa", dialCode: "+685", flag: "\u{1F1FC}\u{1F1F8}" },
  { code: "SM", name: "San Marino", dialCode: "+378", flag: "\u{1F1F8}\u{1F1F2}" },
  { code: "ST", name: "Sao Tome and Principe", dialCode: "+239", flag: "\u{1F1F8}\u{1F1F9}" },
  { code: "SA", name: "Saudi Arabia", dialCode: "+966", flag: "\u{1F1F8}\u{1F1E6}" },
  { code: "SN", name: "Senegal", dialCode: "+221", flag: "\u{1F1F8}\u{1F1F3}" },
  { code: "RS", name: "Serbia", dialCode: "+381", flag: "\u{1F1F7}\u{1F1F8}" },
  { code: "SC", name: "Seychelles", dialCode: "+248", flag: "\u{1F1F8}\u{1F1E8}" },
  { code: "SL", name: "Sierra Leone", dialCode: "+232", flag: "\u{1F1F8}\u{1F1F1}" },
  { code: "SG", name: "Singapore", dialCode: "+65", flag: "\u{1F1F8}\u{1F1EC}" },
  { code: "SX", name: "Sint Maarten", dialCode: "+1721", flag: "\u{1F1F8}\u{1F1FD}" },
  { code: "SK", name: "Slovakia", dialCode: "+421", flag: "\u{1F1F8}\u{1F1F0}" },
  { code: "SI", name: "Slovenia", dialCode: "+386", flag: "\u{1F1F8}\u{1F1EE}" },
  { code: "SB", name: "Solomon Islands", dialCode: "+677", flag: "\u{1F1F8}\u{1F1E7}" },
  { code: "SO", name: "Somalia", dialCode: "+252", flag: "\u{1F1F8}\u{1F1F4}" },
  { code: "ZA", name: "South Africa", dialCode: "+27", flag: "\u{1F1FF}\u{1F1E6}" },
  { code: "GS", name: "South Georgia and the South Sandwich Islands", dialCode: "+500", flag: "\u{1F1EC}\u{1F1F8}" },
  { code: "KR", name: "South Korea", dialCode: "+82", flag: "\u{1F1F0}\u{1F1F7}" },
  { code: "SS", name: "South Sudan", dialCode: "+211", flag: "\u{1F1F8}\u{1F1F8}" },
  { code: "ES", name: "Spain", dialCode: "+34", flag: "\u{1F1EA}\u{1F1F8}" },
  { code: "LK", name: "Sri Lanka", dialCode: "+94", flag: "\u{1F1F1}\u{1F1F0}" },
  { code: "SD", name: "Sudan", dialCode: "+249", flag: "\u{1F1F8}\u{1F1E9}" },
  { code: "SR", name: "Suriname", dialCode: "+597", flag: "\u{1F1F8}\u{1F1F7}" },
  { code: "SJ", name: "Svalbard and Jan Mayen", dialCode: "+47", flag: "\u{1F1F8}\u{1F1EF}" },
  { code: "SE", name: "Sweden", dialCode: "+46", flag: "\u{1F1F8}\u{1F1EA}" },
  { code: "CH", name: "Switzerland", dialCode: "+41", flag: "\u{1F1E8}\u{1F1ED}" },
  { code: "SY", name: "Syria", dialCode: "+963", flag: "\u{1F1F8}\u{1F1FE}" },
  { code: "TW", name: "Taiwan", dialCode: "+886", flag: "\u{1F1F9}\u{1F1FC}" },
  { code: "TJ", name: "Tajikistan", dialCode: "+992", flag: "\u{1F1F9}\u{1F1EF}" },
  { code: "TZ", name: "Tanzania", dialCode: "+255", flag: "\u{1F1F9}\u{1F1FF}" },
  { code: "TH", name: "Thailand", dialCode: "+66", flag: "\u{1F1F9}\u{1F1ED}" },
  { code: "TG", name: "Togo", dialCode: "+228", flag: "\u{1F1F9}\u{1F1EC}" },
  { code: "TK", name: "Tokelau", dialCode: "+690", flag: "\u{1F1F9}\u{1F1F0}" },
  { code: "TO", name: "Tonga", dialCode: "+676", flag: "\u{1F1F9}\u{1F1F4}" },
  { code: "TT", name: "Trinidad and Tobago", dialCode: "+1868", flag: "\u{1F1F9}\u{1F1F9}" },
  { code: "TN", name: "Tunisia", dialCode: "+216", flag: "\u{1F1F9}\u{1F1F3}" },
  { code: "TR", name: "Turkey", dialCode: "+90", flag: "\u{1F1F9}\u{1F1F7}" },
  { code: "TM", name: "Turkmenistan", dialCode: "+993", flag: "\u{1F1F9}\u{1F1F2}" },
  { code: "TC", name: "Turks and Caicos Islands", dialCode: "+1649", flag: "\u{1F1F9}\u{1F1E8}" },
  { code: "TV", name: "Tuvalu", dialCode: "+688", flag: "\u{1F1F9}\u{1F1FB}" },
  { code: "VI", name: "U.S. Virgin Islands", dialCode: "+1340", flag: "\u{1F1FB}\u{1F1EE}" },
  { code: "UG", name: "Uganda", dialCode: "+256", flag: "\u{1F1FA}\u{1F1EC}" },
  { code: "UA", name: "Ukraine", dialCode: "+380", flag: "\u{1F1FA}\u{1F1E6}" },
  { code: "AE", name: "United Arab Emirates", dialCode: "+971", flag: "\u{1F1E6}\u{1F1EA}" },
  { code: "GB", name: "United Kingdom", dialCode: "+44", flag: "\u{1F1EC}\u{1F1E7}" },
  { code: "US", name: "United States", dialCode: "+1", flag: "\u{1F1FA}\u{1F1F8}" },
  { code: "UY", name: "Uruguay", dialCode: "+598", flag: "\u{1F1FA}\u{1F1FE}" },
  { code: "UZ", name: "Uzbekistan", dialCode: "+998", flag: "\u{1F1FA}\u{1F1FF}" },
  { code: "VU", name: "Vanuatu", dialCode: "+678", flag: "\u{1F1FB}\u{1F1FA}" },
  { code: "VA", name: "Vatican City", dialCode: "+379", flag: "\u{1F1FB}\u{1F1E6}" },
  { code: "VE", name: "Venezuela", dialCode: "+58", flag: "\u{1F1FB}\u{1F1EA}" },
  { code: "VN", name: "Vietnam", dialCode: "+84", flag: "\u{1F1FB}\u{1F1F3}" },
  { code: "WF", name: "Wallis and Futuna", dialCode: "+681", flag: "\u{1F1FC}\u{1F1EB}" },
  { code: "EH", name: "Western Sahara", dialCode: "+212", flag: "\u{1F1EA}\u{1F1ED}" },
  { code: "YE", name: "Yemen", dialCode: "+967", flag: "\u{1F1FE}\u{1F1EA}" },
  { code: "ZM", name: "Zambia", dialCode: "+260", flag: "\u{1F1FF}\u{1F1F2}" },
  { code: "ZW", name: "Zimbabwe", dialCode: "+263", flag: "\u{1F1FF}\u{1F1FC}" },
];
