import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service - Komal",
  description:
    "Komal terms of service: usage terms, acceptable use, AI disclaimer, data retention, EULA, refund and cancellation policy for our child safety platform.",
  robots: "index, follow",
  alternates: {
    canonical: "https://komalkids.com/terms-of-service",
  },
};

export default function TermsOfServicePage() {
  return (
    <main>
      <section className="value-prop">
        <div className="container">
          <div className="privacy-policy-content">
            <h1 className="privacy-title">Terms of Service &amp; Legal Agreements</h1>
            <p className="last-updated">
              <strong>Last Updated:</strong> February 22, 2026
            </p>
            <p className="last-updated">
              <strong>Website:</strong>{" "}
              <a href="https://www.komalkids.com">www.komalkids.com</a>
            </p>
            <p className="last-updated">
              <strong>Product:</strong> Komal (&quot;App&quot;, &quot;Service&quot;, or &quot;Platform&quot;)
            </p>

            <div className="privacy-highlight">
              <p>
                By downloading, accessing, or using Komal, you (the &quot;Parent&quot;, &quot;Guardian&quot;, or
                &quot;Account Holder&quot;) agree to be bound by the terms outlined below. If you do not agree to these
                terms, please do not use the Service.
              </p>
            </div>

            <h2>1. Terms of Service (ToS)</h2>

            <h3>1.1. Account Registration and Authority</h3>
            <p>
              To use Komal, you must be at least 18 years of age and the legal parent or guardian of the child whose
              device is being guided. By creating an account, you warrant that you have the legal right to install this
              App on the target device and consent to the use of its in-app controls and AI safety features.
            </p>

            <h3>1.2. Privacy Policy Integration</h3>
            <p>
              Your use of Komal is also governed by our Privacy Policy, which details how we collect, use, and protect
              your data and your child&apos;s data. Please review it at:{" "}
              <a href="/privacy-policy">komalkids.com/privacy-policy</a>.
            </p>

            <h3>1.3. Subscriptions, Payments, and Refunds</h3>
            <p>
              Access to certain AI monitoring and safety features may require an active subscription. Subscriptions
              automatically renew unless canceled at least 24 hours before the end of the current billing period through
              your Apple App Store or Google Play Store account settings. Refunds are handled directly by the respective
              app store according to their policies.
            </p>

            <h3>1.4. Limitation of Liability</h3>
            <p>
              Komal is built to help parents guide how kids use the internet. However, to the maximum extent permitted
              by law, Komal shall not be liable for any indirect, incidental, or consequential damages resulting from
              the use or inability to use the platform, or from exposure to third-party content.
            </p>

            <h2>2. Acceptable Use Policy (AUP)</h2>
            <p>
              Komal is designed strictly for mindful content safety and parental guidance. You agree <strong>NOT</strong>{" "}
              to:
            </p>
            <ul>
              <li>Use the App to monitor any adult, spouse, or employee.</li>
              <li>
                Install the App on a device you do not own or do not have the explicit legal right to manage.
              </li>
              <li>
                Attempt to bypass, reverse-engineer, decompile, or extract the source code or AI algorithms of the App.
              </li>
              <li>
                Use the App for illegal surveillance, stalking, or any purpose outside of child internet safety.
              </li>
            </ul>

            <h2>3. AI and Psychological Disclaimer</h2>

            <h3>3.1. Assistive Tool Only</h3>
            <div className="privacy-highlight">
              <p>
                Komal utilizes artificial intelligence and behavioral signals to filter content, act as a digital buddy,
                and nudge healthier usage. However, Komal is an <em>assistive tool</em> and is not a substitute for
                active, physical parental supervision. While we strive for high accuracy, we cannot guarantee the 100%
                prevention of exposure to all unsafe content.
              </p>
            </div>

            <h3>3.2. No Professional or Medical Advice</h3>
            <div className="privacy-highlight">
              <p>
                <strong>Important:</strong> The behavioral signals, insights, and alerts generated by Komal&apos;s AI
                are for informational and guidance purposes only. The App does not provide medical, psychological, or
                behavioral diagnoses. If you have concerns about your child&apos;s mental health, speech, or emotional
                development, please consult a licensed medical or psychological professional.
              </p>
            </div>

            <h2>4. Data Retention and Deletion Policy</h2>

            <h3>4.1. Parent&apos;s Right to Access and Control</h3>
            <p>
              As the Account Holder, you maintain control over the data collected. You can view the activity processed
              by Komal through your parent dashboard.
            </p>

            <h3>4.2. Right to be Forgotten (Data Erasure)</h3>
            <p>
              You may request the complete deletion of your child&apos;s data and profile at any time. Upon selecting
              &quot;Delete Profile&quot; or &quot;Delete Account&quot; in the App settings, all associated activity
              logs, AI insights, and identifiable information will be permanently purged from our active servers, in
              accordance with app store data safety guidelines.
            </p>

            <h3>4.3. Standard Data Retention Limits</h3>
            <p>
              To ensure data minimization, Komal only retains necessary activity data for a limited period to function
              properly. Once data is no longer needed for its primary safety function, it is securely deleted or
              completely anonymized to improve the AI&apos;s general capabilities.
            </p>

            <h2>5. End-User License Agreement (EULA)</h2>

            <h3>5.1. Grant of License</h3>
            <p>
              Komal grants you a limited, non-exclusive, non-transferable, and revocable license to download, install,
              and use the App on your personal device and the authorized child&apos;s device, strictly in accordance
              with this Agreement.
            </p>

            <h3>5.2. Intellectual Property Rights</h3>
            <p>
              All rights, title, and interest in and to the Komal App—including its AI models, algorithms, design,
              code, and branding—are the exclusive intellectual property of Komal.
            </p>

            <h3>5.3. Termination</h3>
            <p>
              We reserve the right to terminate or suspend your license and account immediately, without prior notice,
              if we determine you have violated any terms in this document, particularly those regarding unauthorized
              surveillance or misuse of the platform.
            </p>

            <h2>6. Refund and Cancellation Policy</h2>

            <h3>6.1. Subscription Cancellations</h3>
            <p>
              You may cancel your Komal premium subscription at any time. Canceling a subscription stops all future
              recurring charges. Your premium access will remain active until the end of your current paid billing
              cycle.
            </p>
            <div className="privacy-highlight">
              <p>
                <strong>Please note:</strong> Deleting the Komal app from your device or deleting your child&apos;s
                profile does not automatically cancel your billing subscription. You must cancel the subscription
                through the platform where you originally purchased it.
              </p>
            </div>

            <h3>6.2. Purchases Made Through the Apple App Store (iOS)</h3>
            <p>
              If you purchased your Komal subscription via the Apple App Store, your payment is processed, managed, and
              controlled entirely by Apple. Komal developers do not have the technical ability to process, approve, or
              issue refunds for Apple purchases. To request a refund, you must contact Apple directly by visiting{" "}
              <a href="https://reportaproblem.apple.com/" target="_blank" rel="noopener noreferrer">
                reportaproblem.apple.com
              </a>{" "}
              and following their standard refund procedures.
            </p>

            <h3>6.3. Purchases Made Through the Google Play Store (Android)</h3>
            <p>
              If you purchased your subscription via the Google Play Store, your payment is managed by Google. You can
              request a refund directly from Google within 48 hours of the purchase by visiting the Google Play Help
              Center. If more than 48 hours have passed, please contact our support team at{" "}
              <a href="mailto:play@komalkids.com">play@komalkids.com</a> with your Google Play Order Number (found on
              your emailed receipt), and we will review your request on a case-by-case basis.
            </p>

            <h3>6.4. Purchases Made Directly on Komalkids.com (Web)</h3>
            <p>
              If you purchased your subscription directly through our website (rather than an app store), we offer a
              14-day refund window for your initial purchase if you experience technical issues that our support team
              cannot resolve. Subscription renewal charges are non-refundable. To request a web-purchase refund, please
              email <a href="mailto:play@komalkids.com">play@komalkids.com</a>.
            </p>

            <h2>Contact Information</h2>
            <div className="contact-info">
              <p>For legal inquiries or support, please contact us at:</p>
              <p>
                <strong>Support Email:</strong>{" "}
                <a href="mailto:play@komalkids.com">play@komalkids.com</a>
              </p>
              <p>
                <strong>Website:</strong>{" "}
                <a href="https://www.komalkids.com">www.komalkids.com</a>
              </p>
            </div>

            <hr className="privacy-divider" />

            <p className="privacy-footer">
              These Terms of Service are effective as of the date listed above and apply to all users of the Komal
              application and website.
            </p>
          </div>
        </div>
      </section>
    </main>
  );
}
